version: "3"
volumes:
  civicconnect_db:
services:
  civicconnect_db:
    container_name: civicconnect_db
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - civicconnect_db:/var/lib/postgresql/data # save data between restarts
    ports:
      - "2430:5432"
